name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always
  # Make sure CI fails on all warnings, including Clippy lints
  RUSTFLAGS: "-Dwarnings"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Build (Debug)
        if: ${{ github.event_name == 'pull_request'}}
        run: cargo build --locked --verbose

      - name: Build (Release)
        if: ${{ github.event_name == 'push' && github.ref_name	== 'main'}}
        run: cargo build --locked --release --verbose

      - uses: actions/upload-artifact@v3
        with:
          name: tic-tac-toe
          path: target/**/tic-tac-toe

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Check
        run: cargo check --verbose
      - name: Run tests
        run: cargo test --verbose

  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Format
        run: cargo fmt --check
      - name: Lint
        run: cargo clippy --all-targets --all-features
